name: 💾 Format

on:
  push:
    branches:
      - main
      - feat/dtt
  pull_request:
    branches:
      - feat/dtt
  release:
    types:
      - created

jobs:
  format:
    name: Format
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v4

      - uses: hecrj/setup-rust-action@v2
        with:
          components: clippy

      - name: Check format
        run: cargo fmt --all -- --verbose
