name: 🧪 Release

on:
  push:
    branches: [main, feat/dtt]
  pull_request:
    branches: [feat/dtt]
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_API_TOKEN }}

jobs:
  build:
    name: Build & Test 🛠
    # Only build/test if pushing to `main`; adjust if needed
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Install Rust stable on the runner
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Cache cargo artifacts to speed up builds
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Test on the specified OS
      - name: Test
        run: cargo test --verbose

      # Build on the specified OS (release mode)
      - name: Build
        run: cargo build --verbose --release

      # Package artifacts (Unix)
      - name: Package (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p target/package
          cd target/release
          tar czf ../../package/${{ matrix.os }}.tar.gz *

      # Package artifacts (Windows)
      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          if (!(Test-Path "target/package")) {
            mkdir target/package
          }
          cd target/release
          tar -czf ../../package/${{ matrix.os }}.tar.gz *

      # Upload artifacts for each OS
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: target/package/${{ matrix.os }}.tar.gz

  release:
    name: Release 🚀
    needs: build
    # Only release if we're pushing to `main`; adjust as you see fit
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        run: echo "VERSION=$(grep -m 1 '^version =' Cargo.toml | cut -d '\"' -f 2)" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate Changelog
        run: |
          echo "## Release v${VERSION} - $(date +'%Y-%m-%d')" > CHANGELOG.md
          cat TEMPLATE.md >> CHANGELOG.md
          git log --pretty=format:'%s' --reverse HEAD >> CHANGELOG.md
          echo "" >> CHANGELOG.md

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: "DateTime (DTT) 🦀 v${{ env.VERSION }}"
          body_path: CHANGELOG.md
          draft: true
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for asset in artifacts/*/*; do
            gh release upload v${{ env.VERSION }} "$asset" --clobber
          done

  crate:
    name: Publish to Crates.io 🦀
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_API_TOKEN }}
        run: cargo publish --token "${{ env.CARGO_REGISTRY_TOKEN }}"
